### ISSUE TITLE
Introduce dynamic columns

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-planning-boards#33]
Rather than 3 hard-coded columns, we need some way to define which columns we show. 

One way to achieve this is with query params. This way the board state (what columns we show, what filters we apply) always lives in the query itself and can be shared across different users.

**Comment by QZera** [comment]
## Initial solution

I store the board state (for now just the columns of the board) in `localStorage`.  (Changes to the columns are persisted between reloads)

Columns are also parsed from the issue labels (each time the issues are fetched). Any new columns are added to the board state.

Added "Import" and "Export" buttons which copy to and read from the clipboard to share board state. 

## Query params

The solution above could be adapted to use the query, although I would probably just use it to set the initial data rather than sync the live data. (Syncing would require real-time communication between `radicle-interface` and `radicle-planning-boards` which while possible, could introduce complexity)

**Comment by QZera** [comment]
# Results

- Added support for persisting board columns(even empty ones) through `localStorage`.
- Added support for creating and deleting columns
  - only empty columns may be deleted
  - `non-planned` and `done` columns cannot be deleted as they are the default columns for issues without a column and closed issues respectively
- Added support for importing/exporting board columns.

https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/1e9fd2b2-5778-4a9f-94ef-accac7ee95df

https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/193953f8-d2f1-4f91-a0fd-7680b538c8fc

**Comment by gsaslis** [comment]
I would still like to explore the query params option a little further, but in the meantime, I think this is already an improvement and we can make it part of the demo prototype.
