### ISSUE TITLE
Allow re-ordering columns

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-planning-boards#38]
I need to be able to re-order columns to visualize my workflow, by dragging & dropping the columns.

**Comment by QZera** [comment]
### RE: Dragging being manually enabled vs always enabled

After some research, I found that a lot of major Kanban Boards have dragging always enabled on their columns. I believe that by doing the same, the UX will be more intuitive than going the other route. What do you think? 

Major Kanban boards with the same UX:
- GitHub
- GitLab
- Trello
- Notion

### Authorization

Since the column state is not on httpd, no authentication or authorization is required to re-order them. Let me know if you would like me to lock this feature behind authentication / the user being a delegate.

cc @gsaslis @maninak

**Comment by gsaslis** [comment]
Yes, this seems enough to have us follow suite.

**Comment by QZera** [comment]
# Results

Added support for re-ordering columns. The order is persisted using LocalStorage.

https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/93b642cb-ee2a-43df-8d6e-edfee70abb95
