### ISSUE TITLE
Support authenticated requests to httpd

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-planning-boards#7]
To perform any mutative request (PUT, PATCH, etc) we need to be authenticated when sending it to `httpd`. GET reqs don't have this restriction.

We need to investigate how radicle-interface does it (they definitely use `rad web`) as well as allow the host app to pass their token to us as a config via Local Storage.

Requires #6

**Comment by QZera** [comment]
`radicle-interface` uses the `Authorization` header along with a token for authentication.

We can use the [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage()) method to [securely](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns) share the authentication token from `radicle-interface` to `radicle-planning-boards`.

This provides us with a IMO very good UX, as the user doesn't need to authenticate twice to use the boards. However, this also means that users can't authenticate in the standalone boards page. (This could be mitigated by adding a LocalStorage flag where the user can manually add their authentication token)

@gsaslis Can we consider sharing the token between the apps enough for this ticket?
Should I add the LocalStorage flag?
Or should I investigate and implement a full authentication system similar to the one in `radicle-interface`?

**Comment by QZera** [comment]
# About Security

## About [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

The `postMessage()` method safely enables cross-origin communication between Window objects; e.g., between a page and a pop-up that it spawned, or between a page and an iframe embedded within it.

In our case, we are using `postMessage` for bi-directional communication between `radicle-interface` and `radicle-planning-boards`.

And in this case specifically, we are examining using `postMessage` to share the authentication token from `radicle-interface` to `radicle-planning-boards` so that `radicle-planning-boards` can make authenticated requests to the `radicle-httpd` API.

## Using [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to share the authentication token securely

Two rules **MUST** be followed to ensure that `postMessage` is used securely:

1. The sender must specify the target origin. This is the URL of the window that will be receiving the message. Only the specified window will receive the message. If the target origin is not specified, the message could be intercepted by a malicious site.
    - In our case, `radicle-interface` should specify the target origin as the origin of the `radicle-planning-boards` (i.e. `rpb.radicle.xyz`). And `radicle-planning-boards` should specify the target origin as the origin of `radicle-interface` (i.e. `app.radicle.xyz`).

2. The receiver must verify the origin, as well as the syntax of the message. If the origin is not trusted, or the syntax isn't expected the message should be ignored.
    - In our case, `radicle-planning-boards` should verify that the origin of the message is the one from `radicle-interface`. And `radicle-interface` should verify that the origin of the message is the one from `radicle-planning-boards`.

## General security

The [nuxt-security](https://nuxt-security.vercel.app/) library has been used, which provides great defaults for securing the application against common attacks. For example the `Content-Security-Policy` `frame-ancestors` directive has been configured so that only the `radicle-interface` source is allowed to open the `radicle-planning-boards` iframe.

## Sources

- <https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage>
- <https://security.stackexchange.com/a/170745>
- <https://book.hacktricks.xyz/pentesting-web/postmessage-vulnerabilities>

**Comment by QZera** [comment]
# Results

Added support for receiving and using authentication token from `radicle-interface`

**Comment by gsaslis** [comment]
Ok, thanks for elaborating and capturing this information here. 

Looks Good To Me (LGTM) 👍
